### PR TITLE
788 misc priority fixes

### LINKED ISSUE #788: [FEATURE] Misc Priority Fixes
### Issue to be solved

— FTUE Improvements — 

- In send, it should default to open the “My accounts” tab and have it as the left-most item.

- Remove move assets button on the dashboard

- Move activity to be a bottom tab-bar item

- Stake button on the dashboard should open the “Node providers list” directly, not show an empty staking list if the user has not already staked

- On FTUE, the user should have to have to start the backup flow before being able to use the rest of the app.
     - Remove the "Maybe later" button so they can't exit the flow that way.
     - Add an alert when they try to back out of the backup flow.

- Fix google drive issues on multi-backup workflow

- On Import Wallet workflow, change “From Recovery Phrase (legacy)” to “Other”
  - Change the title to “Import Wallet” without unnecessary capitalization.

— Other —

On app explorer:

- Remove the “view” tab on top
- Fix the “Apps” title to be the same height as the title on the collections page.

On NFT/Collection view

- Remove the “List”/”Grid” selector
- Always use the “List” view logic.

### Suggest A Solution

_No response_

### PR DESCRIPTION
**Pull request by martyu**
## Related Issue

https://github.com/Outblock/FRW-iOS/issues/788

## Summary of Changes

-remove extra List/Grid toggle.
- Remove the “view” tab on top Fix the “Apps” title to be the same height as the title on the collections page.	
- fix localization fix backwards light/dark mode for help icon	
- In send, it should default to open the “My accounts” tab and have it as the left-most item.	
- Stake button on the dashboard should open the “Node providers list” directly, not show an empty staking list if the user has not already staked
- remove "Maybe Later" to force backing up keys.	
- Strings tweaks Make whole "Welcome" cell tappable.	
- Remove "Move Assets" button from home screen

## Need Regression Testing

- [ ] Yes
- [x] No

## Risk Assessment

- [x] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: FRW/Services/Router/RouteMap.swift [hunk 1]
```diff
@@ -296,6 +296,9 @@ extension RouteMap.Wallet: RouterTarget {
             navi.present(content: AddTokenView(vm: vm))
         case .stakingList:
             navi.push(content: StakingListView())
+            if StakingManager.shared.isStaked == false {
```
Comment (zhouxl) [inline FRW/Services/Router/RouteMap.swift:299]: will push two view？

Comment (zhouxl) [reply FRW/Services/Router/RouteMap.swift:299]: Will this problem happen

**Review by zhouxl — APPROVED** [review]
