### PR TITLE
fix: key is not on the server.

### LINKED ISSUE #563: Failed to import wallet from cloud backup
# :clipboard: Bug Details

>Failed to import wallet from cloud backup 

key | value
--|--
Reported At | 2025-10-15 00:03:00 UTC
Categories | Report a bug
App Version | 3.0.2 (205)
Session Duration | 92
Device | iPhone18,2, iOS 26.0.1
Display | 440x956 (@3x)
Location | Mesa, United States (en-US)

## :point_right: [View Full Bug Report on Instabug](https://dashboard.luciq.ai/applications/flow-foundation/production/bugs/327?utm_source=github&utm_medium=integrations) :point_left:
___
# :chart_with_downwards_trend: Session Profiler
Here is what the app was doing right before the bug was reported:

Key | Value
--|--
CPU Load | 3.4%
Used Memory | 1.3% - 0.04/3.3 GB
Used Storage | 43.6% - 207.79/476.24 GB
Connectivity | WiFi
Battery | 60% - unplugged
Orientation | portrait

Find all the changes that happened in the parameters mentioned above during the last 60 seconds before the bug was reported here:  :point_right: **[View Full Session Profiler](https://dashboard.luciq.ai/applications/flow-foundation/production/bugs/327?show-session-profiler=true&utm_source=github&utm_medium=integrations)** :point_left:
___
# :warning: Looking for More Details?
1. **Network Log**: we are unable to capture your network requests automatically. If you are using AFNetworking or Alamofire, [**check the details mentioned here**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations#section-requests-not-appearing-in-logs).
2. **User Steps**: [**enable them**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations#section-user-steps) to get the most out of your plan and see every action users take before reporting a bug.
3. **User Events**: start capturing custom User Events to send them along with each report. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).
4. **Instabug Log**: start adding Instabug logs to see them right inside each report you receive. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).
5. **Console Log**: when enabled you will see them right inside each report you receive. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).

### PR DESCRIPTION
**Pull request by zhouxl**
## Related Issue

Links https://github.com/onflow/FRW-monorepo/issues/563

## Need Regression Testing

- [ ] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: FRW/Modules/MultiRestore/ViewModel/RestoreMultiAccountViewModel.swift [hunk 1]
```diff
@@ -52,9 +52,13 @@ class RestoreMultiAccountViewModel: ObservableObject {
                     MultiAccountStorage.shared.setBackupType(.multi, uid: selectedUserId)
                     HUD.dismissLoading()
                 } catch {
```
Comment (lmcmz) [inline FRW/Modules/MultiRestore/ViewModel/RestoreMultiAccountViewModel.swift]: Try with this, swift should able to catch specific error
```suggestion
               catch LLError.accountNotFound {
                  addKey(item: selectedUser)
                } catch {
                  log.error("switch account failed", context: error)
                  HUD.dismissLoading()
                  HUD.error(title: error.localizedDescription)
                  return
                }
```

**Review by lmcmz — DISMISSED** [review]

**Review by lmcmz — APPROVED** [review]
