### PR TITLE
fix： #819 receiver incorret warning when send

### LINKED ISSUE #819: [BUG] Incorrect receiver vault setup warning when moving FT
### Describe the Bug

- When moving certain FT from your own EVM to Cadence accounts, an incorrect receiver vault setup warning is displayed.

Image

### Expected experience

- When moving FT from your own EVM account to your own Cadence account, the correct vault is automatically setup for your cadence account if not already created.

### Steps To Reproduce

1. Aquire some stgUSDC to your EVM account
2. Move the stgUSDC to your Cadence account
3. Observe the incorrect warning displayed

### Environment

```markdown
- iOS 2.3.6
```

### PR DESCRIPTION
**Pull request by zhouxl**
## Related Issue

Closes #819 

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

**Comment by lmcmz** [comment]
Which line has changed?
Meanwhile, can we run a swiftformat for the whole project ?
Otherwise, it's so hard to review the code.

Cause I need identify which changes is made by formatter which made by you.

File: FRW/Modules/Wallet/Send/WalletSendAmountViewModel.swift [hunk 1]
```diff
@@ -147,14 +159,16 @@ extension WalletSendAmountViewModel {
...
                     await MainActor.run {
                         self.isValidToken = false
                     }
                     return
                 }
-                let list = try await FlowNetwork.checkTokensEnable(address: Flow.Address(hex: address))
-                let model = list.first { $0.key.lowercased() == compareKey.lowercased() }
+                let list = try await FlowNetwork
+                    .checkTokensEnable(address: Flow.Address(hex: address))
+                let model = list.first { compareKey.lowercased().contains($0.key.lowercased()) }
```
Comment (lmcmz) [inline FRW/Modules/Wallet/Send/WalletSendAmountViewModel.swift:171]: Could you provide an example ?
Why we use contains instead of equal ?

Comment (zhouxl) [reply FRW/Modules/Wallet/Send/WalletSendAmountViewModel.swift:171]: @lmcmz 
flowIdentifier of token on evm side has contain `Vault`, but list of the cadence of `checkTokensEnable` don't contain `Vault`, I don't want to do the extra work
```swift
A.address.name.Vault
A.adress.name
```

**Comment by zhouxl** [comment]
> Which line has changed? Meanwhile, can we run a swiftformat for the whole project ? Otherwise, it's so hard to review the code.
> 
> Cause I need identify which changes is made by formatter which made by you.

It was not unified before

**Review by lmcmz — APPROVED** [review]
