### PR TITLE
957 bug refresh activity tab when account changes

### LINKED ISSUE #957: [BUG] Refresh Activity tab when account changes.
### Describe the Bug

Activity tab transaction list doesn't update on account change.

### Expected experience

Activity tab should refresh automatically on account change.

### Steps To Reproduce

1) Look at Activity tab's transaction list.
2) Switch accounts.
3) Go back to Activity tab.
4) You need to pull-to-refresh to update the list.

### Environment

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by martyu**
## Related Issue

#957

## Summary of Changes

Refresh transaction list on account change.

## Need Regression Testing

- [ ] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: FRW/Services/Token/TokenBalanceHandler.swift [hunk 1]
```diff
@@ -115,9 +115,6 @@ class TokenBalanceHandler {
     }
 
     func getAllNFTsUnderCollection(address: FWAddress, collectionIdentifier: String, network: FlowNetworkType = LocalUserDefaults.shared.flowNetwork, progressHandler: @escaping (Int, Int) -> Void) async throws -> [NFTModel] {
-        guard let collection = try await getNFTCollections(address: address).first(where: { $0.id == collectionIdentifier }) else {
-            throw TokenBalanceProviderError.collectionNotFound
-        }
```
Comment (zhouxl) [inline FRW/Services/Token/TokenBalanceHandler.swift:139]: Why remove this？

File: FRW/Modules/TransactionList/TransferListHandler.swift [hunk 2]
```diff
@@ -111,6 +111,12 @@ class TransferListHandler: TransactionListBaseHandler {
         }
 
         collectionView.beginRefreshing()
+        
+        Task { [weak self] in
```
Comment (zhouxl) [inline FRW/Modules/TransactionList/TransferListHandler.swift:115]: 1. Will this lead to memory leaks?
2. Not in the main thread

Comment (martyu) [reply FRW/Modules/TransactionList/TransferListHandler.swift:115]: 1. It should prevent leaks, right?
2. All UIKit classes are `@MainActor`, that's why the `beginRefreshing()` inside the Task requires an `await` and the one outside the Task doesn't.
(If TransferListHandler was marked with `@MainActor`, then this Task would inherit `@MainActor` also, since it's not `Task.detached`.

File: FRW/Services/Token/TokenBalanceHandler.swift (hunk 1 above)
Comment (martyu) [reply FRW/Services/Token/TokenBalanceHandler.swift:139]: This is from before we added the Providers I think. `collection` isn't used, and we do the same call in the Providers.

**Review by lmcmz — DISMISSED** [review]

**Comment by martyu** [comment]
@lmcmz fyi i cant merge this, one of you would need to.

**Review by zhouxl — APPROVED** [review]
