### PR TITLE
460 Allow add EOA address in customised address book

### LINKED ISSUE #460: [FEATURE] Allow add EOA address in customised address book
**Description:**

I would like to request a feature that allows users to add Externally Owned Account (EOA) addresses to their customized address book. Currently, when I try to add an EOA address, I receive an error stating, "This address is invalid."

**Current Behavior:**

When attempting to add an EOA address, the system returns an error message indicating that the address is invalid.

**Expected Behavior:**

Users should be able to successfully add valid EOA addresses to their customized address book without encountering error messages.

**Steps to Reproduce:**

(1) Navigate to the address book.
(2) Attempt to add a valid EOA address.
(3) Observe the error message stating, "This address is invalid."

### PR DESCRIPTION
**Pull request by jeden**
https://github.com/Outblock/FRW-iOS/issues/460

### CODE REVIEW

File: FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift [hunk 1]
```diff
@@ -256,29 +261,39 @@ extension AddAddressView {
                 return
             }
 
-            var formatedAddress = state.address.trim().lowercased()
-            if !formatedAddress.hasPrefix("0x") {
-                formatedAddress = "0x" + formatedAddress
+            var formattedAddress = state.address.trim().lowercased()
+            if !formattedAddress.hasPrefix("0x") {
```
Comment (lmcmz) [inline FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift]: use `addHexPrefix` instead

File: FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift [hunk 2]
```diff
@@ -80,7 +81,11 @@ extension AddAddressView {
         case save
     }
 
-    class AddAddressViewModel: ViewModel {
+    final class AddAddressViewModel: ViewModel {
+        enum AddressType {
+            case flow, eoa
```
Comment (lmcmz) [inline FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift]: The type should be `flow` and `evm`

File: FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift [hunk 3]
```diff
@@ -298,6 +313,20 @@ extension AddAddressView.AddAddressViewModel {
         DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: task)
     }
 
+    private func checkEoaAddressExists(_ address: String) {
+        guard let eoa = EthereumAddress(address, type: .normal, ignoreChecksum: false) else {
```
Comment (lmcmz) [inline FRW/Modules/Profile/AddressBook/Add/AddAddressViewModel.swift]: `ignoreChecksum` should be true.
```swift
 guard let eoa = EthereumAddress(address, ignoreChecksum: true) else {
 ```

**Review by lmcmz — CHANGES_REQUESTED** [review]

**Review by lmcmz — APPROVED** [review]
