### PR TITLE
907 feature display fractional cent usd prices values in the correct format

### LINKED ISSUE #838: [Tech only] Unit testing env is broken
Need fix the unit testing env

No need for QA

### LINKED ISSUE #907: [FEATURE] Display fractional cent USD prices / values in the correct format
### Issue to be solved

Display fractional cent USD prices / values in the correct format

For tokens with prices or values below 1 cent (eg: $0.0000001), we must display these values in the correct formats.

- We should only display up to 4 decimals of precision.
- We should always display at least 2 decimals of precision
- If the value is below $0.0001, we must display the value using the required subscript format. 
  - For the number of leading zeros, use the format 0 followed by the number of leading zeros in subscript notation.
    - For example: $0.00000023 would be displayed as $0.0₆23
  - Include at most 3 decimals of precision after the the subscript notation.
    - For example: $0.000003345 would be displayed as $0.0₅335
- Where required, always round up.

### Suggest A Solution

_No response_

### PR DESCRIPTION
**Pull request by martyu**
## Related Issue

Closes 907.

## Summary of Changes

Add formatting for lots of 0s.

## Need Regression Testing

- [ ] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [ ] Medium
- [ ] High

## Screenshots (if applicable)

https://github.com/user-attachments/assets/3eee81ee-e3f7-48c0-89c6-d57d514a1cd5

### CODE REVIEW

File: FRWTests/FlowReferenceWalletTests.swift [hunk 1]
```diff
@@ -26,39 +26,24 @@ struct NewStakingInfoInner: Codable {
...
-            )
-            .decode([NewStakingInfoInner].self)
-
-            print(model)
-        } catch {
-            print(error)
-        }
-    }
+    
+//    func testStakeDecode() async throws {
```
Comment (martyu) [inline FRWTests/FlowReferenceWalletTests.swift:30]: This test was failing.

**Review by zhouxl — APPROVED** [review]
