### PR TITLE
fix: checksum will return “0x” if address is “”,

### LINKED ISSUE #928: [BUG] Display "Enable EVM" Banner Instead of "0x EVM Account" for Accounts Without EVM Account
**Description:** 
Currently, accounts without an EVM account are displayed as "0x EVM Account." However, we need to update this behavior and show a banner prompting users to enable EVM instead.

**Steps to Reproduce:**

(1)import an account that does not have an EVM account.
(2) View the account side bar.

**Expected Behavior:**
 For accounts without an EVM account, a banner should appear indicating that the user can enable EVM, rather than displaying "0x EVM Account."

**Actual Behavior:** 
Accounts without an EVM account are shown as "0x EVM Account."

Image

### PR DESCRIPTION
**Pull request by zhouxl**
## Related Issue

Closes #928 
## Summary of Changes

checksum return "0x" when address is empty.

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [x] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: FRW/Services/Manager/EVMAccountManager.swift [hunk 1]
```diff
@@ -167,7 +167,7 @@ extension EVMAccountManager {
             return
         }
 
-        if let EVMAddress = cacheAccounts[primaryAddress]?.first {
+        if let EVMAddress = cacheAccounts[primaryAddress]?.first, EVMAddress.count > 2 {
```
Comment (lmcmz) [inline FRW/Services/Manager/EVMAccountManager.swift]: Use `if let evmAddress = EthereumAddress(EVMAddress)` instead of `EVMAddress.count > 2`

**Review by lmcmz — CHANGES_REQUESTED** [review]

**Review by lmcmz — APPROVED** [review]
