### PR TITLE
499 Inconsistent padding

### LINKED ISSUE #499: Inconsistent padding
# :clipboard: Bug Details

>Inconsistent padding 

key | value
--|--
Reported At | 2024-11-08 10:18:10 UTC
Email | jeffrey.doyle@flowfoundation.org
Categories | Suggest an improvement
App Version | 2.2.9 (10)
Session Duration | 75
Device | iPhone 13 Pro, iOS 17.6.1
Display | 390x844 (@3x)
Location | Bangkok, Thailand (en-CA)

## :point_right: [View Full Bug Report on Instabug](https://dashboard.instabug.com/applications/flow-foundation/production/bugs/137?utm_source=github&utm_medium=integrations) :point_left:
___
# :chart_with_downwards_trend: Session Profiler
Here is what the app was doing right before the bug was reported:

Key | Value
--|--
CPU Load | 48.7%
Used Memory | 7.0% - 0.21/3.0 GB
Used Storage | 97.9% - 233.3/238.3 GB
Connectivity | NA - NA
Battery | 30% - plugged
Orientation | portrait

Find all the changes that happened in the parameters mentioned above during the last 60 seconds before the bug was reported here:  :point_right: **[View Full Session Profiler](https://dashboard.instabug.com/applications/flow-foundation/production/bugs/137?show-session-profiler=true&utm_source=github&utm_medium=integrations)** :point_left:
___
# :mag_right: Logs
### Network Log
This bug report has **2 failed** (4xx, 5xx or no response) requests. Here are some of them:
```
10:13:14 400 POST https://rest-mainnet.onflow.org/v1/scripts?block_height=sealed
10:17:17 400 POST https://rest-mainnet.onflow.org/v1/scripts?block_height=sealed

```
Find all the network requests with more details about each one, its duration, method, URL, headers, and response here:  :point_right: **[View Detailed Network Logs](https://dashboard.instabug.com/applications/flow-foundation/production/bugs/137?show-logs=network_log&utm_source=github&utm_medium=integrations)** :point_left:

___
# :camera: Images
[image attachment](https://d38gnqwzxziyyy.cloudfront.net/attachments/bugs/23226997/2e41ee9e10d7d34720fc66fd07bb5408_original/36890604/2024110805180315857782.jpg?Expires=4886734697&Signature=J4gFk6cg4A052lGYgDdXLhF7xJ3JverUhZ7zsRSE45VbSCLbAtYNdwbF2wPy~ljPKIMQ8H-66n9GbyoxhUXti51Ayeqr3BMW3I8TSKmRiKo2mNgTRAgL0VWjO8rCuLGVRvDA-u~2wUfJmJSxsOKLCtn-XZqMgBXkgGpztXqOXRhTMol-~RhOXwr13v3I6zIDY37JIzn-CWorFGtvKsc2ZgD8KIJdP53TgU6FY24PS4x96MpDEBffE8sfUM0A0q-0A3isbsXVreu3n02yYtDi7~UMoRtL7ancNLyWo19B-JOwSJW3nBjsFT0X5Ev4Gljh5iHciwlZKClgKPeNKWfzYA__&Key-Pair-Id=APKAIXAG65U6UUX7JAQQ)

___
# :warning: Looking for More Details?
1. **User Steps**: [**enable them**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations#section-user-steps) to get the most out of your plan and see every action users take before reporting a bug.
2. **User Events**: start capturing custom User Events to send them along with each report. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).
3. **Instabug Log**: start adding Instabug logs to see them right inside each report you receive. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).
4. **Console Log**: when enabled you will see them right inside each report you receive. [**Find all the details in the docs**](https://docs.instabug.com/docs/ios-logging?utm_source=github&utm_medium=integrations).

### PR DESCRIPTION
**Pull request by jeden**
## Related Issue

- Ticket: https://github.com/Outblock/FRW-iOS/issues/499
- Follow-up: #647 

## Summary of Changes

**Note: in this PR the min iOS version has been increased to 16.**

Some implementation details:
- iOS automatically chooses how to position the visible area when the keyboard is visible. If there's enough real estate, the bottom button is completely visible, positioned right above the keyboard. In case of not enough space, it seems to keep the edited text field at the vertical center of the visible area above the keyboard.
- Adding a scroll view (with or without a geometry reader) invalidates the height calculation and causes the sheet view to not be displayed at all (except for a small frame at the bottom). If the view is not scrollable it works fine. This shouldn't be a major issue though, with larger text the bottom button might go out of the visible space, and so does the title area, but the text edit should still remain visible.

Only the `halfSheet()` modifier, and corresponding places where it is used, have been refactored. 

`PresentHostingController` and `CustomHostingController` require additional refactoring that will be addressed on a separate ticket (#647)

## Need Regression Testing

- [X] Yes: all UI places where pull-up sheets are displayed
- [ ] No

## Risk Assessment

- [ ] Low
- [X] Medium: any implementation mistake can lead to incorrect layouts that might affect UX
- [ ] High

## Screenshots (if applicable)

See [this comment](https://github.com/Outblock/FRW-iOS/pull/596#issuecomment-2529678553) for a list of screenshots where the half sheet is used.

### CODE REVIEW

File: FRW/Modules/Wallet/MoveAsset/MoveComponentView.swift [hunk 1]
```diff
@@ -127,9 +127,10 @@ struct MoveFeeView: View {
             }
             .frame(height: 16)
             Text(feeHint())
+                .lineLimit(nil)
+                .fixedSize(horizontal: false, vertical: true)
```
Comment (jeden) [inline FRW/Modules/Wallet/MoveAsset/MoveComponentView.swift:131]: This enables the text to be displayed in multiple lines, if needed, otherwise it stays on a single line and wrapped if necessary.

**Comment by zhouxl** [comment]
custom height is only on iOS 16 and up？

**Comment by lmcmz** [comment]
Can we have a horizontal solution cross the app ? 
Cause this is no an issue on this page only, We have many place need adjust dynamic height.

**Comment by lmcmz** [comment]
Meanwhile, when I put more elements in this bottom sheet, it doesn't dynamic adjust the content height.
IMG_4624

**Comment by jeden** [comment]
> custom height is only on iOS 16 and up？

@zhouxl I thought I had answered to this question...  maybe it was in the other PR that I closed.

Anyway yes, unfortunately this works on iOS 16+ only

**Comment by jeden** [comment]
> Can we have a horizontal solution cross the app ? Cause this is no an issue on this page only, We have many place need adjust dynamic height.

@lmcmz Yes, the implementation is reusable, but it requires some minor refactoring on a case-by-case basis, similar to what done in `MoveTokenView.swift`

**Comment by jeden** [comment]
> Meanwhile, when I put more elements in this bottom sheet, it doesn't dynamic adjust the content height. 
@lmcmz 
What have you added? Can you share the code so I can take a look?

**Comment by jeden** [comment]
> > Meanwhile, when I put more elements in this bottom sheet, it doesn't dynamic adjust the content height.
> > @lmcmz
> > What have you added? Can you share the code so I can take a look?

nvm... I see you've duplicated the source-target row. I'll check that out

**Comment by jeden** [comment]
@lmcmz what device and iOS version are you on?

This is taken from the iPhone 15 Pro (simulator), iPhone SE (simulator):

image
image


And this from my iPhone 15 Pro (device)
image

**Comment by lmcmz** [comment]
This move token view can be init from multiple places. The one I tested from home screen doesn't work.

I would suggest we apply this dynamic height configuration in all places using 
```
CustomHostingController
halfSheet
PresentHostingController
```

**Comment by lmcmz** [comment]
Meanwhile, I can see this bottom sheet have a transparent background on bottom safe area. We need fix this.

Probably, we fix on different PR, the insufficient storage alert shown't overlap with the move fee UI, it was overlap due to the height is not dynamic.

Screenshot 2024-12-03 at 12 10 59 am

**Comment by jeden** [comment]
> This move token view can be init from multiple places. The one I tested from home screen doesn't work.

Can we meet today so you can show me in which case it does not work? Because I am unable to reproduce that.

> I would suggest we apply this dynamic height configuration in all places using
> 
> ```
> CustomHostingController
> halfSheet
> PresentHostingController
> ```

I suggest deferring this to a separate ticket, to prevent this from being out of sync with develop again.

**Comment by jeden** [comment]
> Meanwhile, I can see this bottom sheet have a transparent background on bottom safe area. We need fix this.
> 
> Probably, we fix on different PR, the insufficient storage alert shown't overlap with the move fee UI, it was overlap due to the height is not dynamic.
> 
> Screenshot 2024-12-03 at 12 10 59 am

The button is on an overlay, so it doesn't contribute to the underlying view's height — and the alert is displayed in the same overlay (because it's linked to the button). In order for that to happen I should move the button from the overlay to the view.

**Comment by lmcmz** [comment]
It doesn't fit when there is a keyboard 
IMG_4630

**Comment by lmcmz** [comment]
It doesn't look good when there is a keyboard
IMG_4630

**Comment by jeden** [comment]
Yeah I haven't reworked on that after the discussions of the past couple days

**Comment by lmcmz** [comment]
Not sure, why we are not continue working on this. 
We need meet following requirements:
1. Adapted for keyboard input scenarios
2. The bottom safe area has no background
3. We need apply this auto resize to all our bottom sheet popup.

**Comment by jeden** [comment]
This is what I have been working on in the latest days. I haven't pushed any commit since I needed to fix the layout issues first and then check and refactor all places where the half sheet is used.

I should resubmit this for review today or tomorrow. However I think I'll defer the other 2 usages (`PresentHostingController` and `CustomHostingController`) to a separate ticket, because this is diverging too much from dev and merging might become more complicated the more I wait.

**Comment by jeden** [comment]
1. backup tips shown on home

image

2. settings -> devices -> device info -> key location -> swipe left -> tap "Revoke": 

image

3. home -> plus button -> tap any circled plus button

image

4. settings -> backup -> multi-backup -> swipe left any backup -> tap "Delete"

image

5. settings -> linked accounts -> any child account -> tap "Unlink Account"

image

6. settings -> backup -> multi-backup -> tap any -> tap "Delete Backup"

image

7. NFT -> tap plus button -> any NFT, tap circular plus button

image

8. NFT -> tap any NFT -> tap the "Move" button

image

9. home -> tap "Stake" button -> tap "Stake New Node" -> tap any token -> input amount -> tap "Next"

image

10. home -> tap any token -> tap swap button -> type amount -> select destination token -> tap "Swap beta"

image

11. home -> tap any token -> tap "move" button

image

12. home -> tap any token -> tap send button -> select recipient -> type amount -> tap "Next"

image

**Review by lmcmz — APPROVED** [review]
